version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo "🔧 Building shared Lambda layer"
      - cd shared_layer
      - bash build.sh
      - cd ..

  build:
    commands:
      - echo "🚀 Building FastAPI Lambdas"
      - sam build

  post_build:
    commands:
      - echo "🚀 Deploying stack via SAM"
      - sam deploy \
          --stack-name pipeflow-stack \
          --capabilities CAPABILITY_IAM \
          --region ap-south-1 \
          --no-fail-on-empty-changeset \
          --no-confirm-changeset
