version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "✅ Installing AWS SAM CLI"
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "📦 Skipping global dependency install"
  build:
    commands:
      - echo "🔨 Building SAM Application"
      - sam build
  post_build:
    commands:
      - echo "🚀 Deploying stack via SAM"
      - sam deploy --stack-name pipeflow-stack-v2 --capabilities CAPABILITY_IAM --region ap-south-1 --resolve-s3 --no-fail-on-empty-changeset --no-confirm-changeset

artifacts:
  files:
    - template.yaml
