version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18  # ✅ REQUIRED for Serverless Framework
    commands:
      - echo "✅ Installing Serverless Framework CLI"
      - npm install -g serverless@3.38.0
      - pip install -r shared_layer/requirements.txt

  pre_build:
    commands:
      - echo "📦 Building shared layer before Serverless deploy"
      - cd shared_layer
      - bash build.sh
      - cd ..

  build:
    commands:
      - echo "🔨 No separate build step needed for Serverless Framework"

  post_build:
    commands:
      - echo "🚀 Deploying stack via Serverless Framework"
      - serverless deploy --stage dev --region ap-south-1

artifacts:
  files:
    - serverless.yml
