service: pipeflow

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ap-south-1
  stage: dev

layers:
  shared:
    path: shared_layer
    compatibleRuntimes:
      - python3.11

functions:
  masterdata:
    handler: masterdata_lambda/main.handler
    layers:
      - { Ref: SharedLambdaLayer }
    functionUrl:  # Enable direct Lambda URL
      authType: NONE

  networkflow:
    handler: networkflow_lambda/main.handler
    layers:
      - { Ref: SharedLambdaLayer }
    functionUrl:
      authType: NONE

  tenant:
    handler: tenant_lambda/main.handler
    layers:
      - { Ref: SharedLambdaLayer }
    functionUrl:
      authType: NONE

  userrole:
    handler: user_role_permission_lambda/main.handler
    layers:
      - { Ref: SharedLambdaLayer }
    functionUrl:
      authType: NONE

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
