AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pipeflow-shared-layer
      ContentUri: shared_layer/shared_layer.zip
      CompatibleRuntimes:
        - python3.11

  TenantLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tenant-lambda
      Handler: main.handler
      CodeUri: tenant_lambda/
      Layers:
        - !Ref SharedLayer
      FunctionUrlConfig:
        AuthType: NONE

  MasterDataLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: masterdata-lambda
      Handler: main.handler
      CodeUri: masterdata_lambda/
      Layers:
        - !Ref SharedLayer
      FunctionUrlConfig:
        AuthType: NONE

  NetworkFlowLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: networkflow-lambda
      Handler: main.handler
      CodeUri: networkflow_lambda/
      Layers:
        - !Ref SharedLayer
      FunctionUrlConfig:
        AuthType: NONE

  RolePermissionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: role-permission-lambda
      Handler: main.handler
      CodeUri: user_role_permission_lambda/
      Layers:
        - !Ref SharedLayer
      FunctionUrlConfig:
        AuthType: NONE
